- id: set_google_home_slider_position
  alias: Set Google Home Slider Position
  trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
  condition:
  - condition: template
    value_template: '{{ not is_state_attr("media_player.bedroom_speaker", "volume_level",
      states("input_number.home_volume") | int / 100) }}'
  action:
  - service: input_number.set_value
    entity_id: input_number.home_volume
    data:
      value: '{{ trigger.to_state.attributes.volume_level | multiply(100) | int }}'
- id: set_google_home_volume
  alias: Set Google Home Volume
  trigger:
  - platform: state
    entity_id: input_number.home_volume
  condition:
  - condition: template
    value_template: '{{ not is_state_attr("media_player.bedroom_speaker", "volume_level",
      states("input_number.home_volume") | int / 100) }}'
  action:
  - service: media_player.volume_set
    entity_id: media_player.bedroom_speaker
    data:
      volume_level: '{{ states("input_number.home_volume") | int / 100 }}'
- id: '1598304909639'
  alias: Restart HA core
  description: Restart HA core every 2~3 days
  trigger:
  - at: 04:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
    - tue
    - thu
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
- id: spotify_album_art
  alias: Sync spotify lights
  initial_state: false
  trigger:
    - platform: state
      entity_id: media_player.spotify_mark_shui_hu
  action:
    - service: color_extractor.turn_on
      data:
        color_extract_url: '{{ states.media_player.spotify_mark_shui_hu.attributes.entity_picture }}'
        entity_id: light.strip
- id: enable_spotify_album_art
  alias: Enables or disables syncing of spotify album art
  trigger:
    - platform: state
      entity_id: input_boolean.switch_spotify_lights
  action:
    - service: automation.turn_{{ states.input_boolean.switch_spotify_lights }}
      entity_id: automation.spotify_album_art
