- id: set_google_home_slider_position
  alias: Set Google Home Slider Position
  trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
  condition:
  - condition: template
    value_template: '{{ not is_state_attr("media_player.bedroom_speaker", "volume_level",
      states("input_number.home_volume") | int / 100) }}'
  action:
  - service: input_number.set_value
    entity_id: input_number.home_volume
    data:
      value: '{{ trigger.to_state.attributes.volume_level | multiply(100) | int }}'
- id: set_google_home_volume
  alias: Set Google Home Volume
  trigger:
  - platform: state
    entity_id: input_number.home_volume
  condition:
  - condition: template
    value_template: '{{ not is_state_attr("media_player.bedroom_speaker", "volume_level",
      states("input_number.home_volume") | int / 100) }}'
  action:
  - service: media_player.volume_set
    entity_id: media_player.bedroom_speaker
    data:
      volume_level: '{{ states("input_number.home_volume") | int / 100 }}'
- id: '1598304909639'
  alias: Restart HA core
  description: Restart HA core every 2~3 days
  trigger:
  - at: 04:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
    - tue
    - thu
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
- id: '1607945958210'
  alias: Auto mirror light
  description: Automatically turns on mirror light onmotion
  trigger:
  - platform: state
    entity_id: binary_sensor.tradfri_motion_sensor
  condition: []
  action:
  - service: "{% if trigger.to_state.state == \"on\" %}\n  light.turn_on\n{% else\
      \ %}\n  light.turn_off\n{% endif %}\n"
    data:
      entity_id: switch.desk_top_mirror
  mode: single
- id: '1610459546154'
  alias: Light scene selector
  description: Auto update light scene from input select
  trigger:
  - platform: state
    entity_id: input_select.light_scene
  condition: []
  action:
  - service: script.turn_on
    data:
      entity_id: script.{{ trigger.to_state.state }}_light
  mode: single
