- id: set_dark_theme_at_start
  alias: 'Set theme at startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: midnight

# # Refresh every 5 minutes to check of wakeuplight time
# - id: refresh_wakeup_light
#   alias: 'Wakeup light check'
#   trigger:
#     - platform: homeassistant
#       event: start
#     - platform: time_pattern
#       minutes: '/5'
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.set_wake_light

# Auto set alarm at 10pm
- id: auto_set_alarm_10pm
  alias: "Auto set alarm at 10pm"
  trigger:
    platform: time
    at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.switch_autoalarm
      state: "on"
    - condition: state
      entity_id: input_boolean.switch_alarm
      state: "off"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.switch_alarm
    - service: tts.google_translate_say
      entity_id: media_player.bedroom_speaker
      data_template:
        message: '{{ "Good evening. Your alarm has been automatically set at" + states("input_number.alarm_hours") + " " + states("input_number.alarm_minutes") }}'

# On wakeuplight time, turn on lights and set wakeuplight off time
- id: alarm_wakeup_light
  alias: 'Wakeup lights'
  trigger:
    platform: state
    entity_id: sensor.alarm_m10_sensor
  condition:
    condition: state
    entity_id: input_boolean.switch_alarm
    state: "on"
  action:
    - service: script.turn_on
      data:
        entity_id: script.alarm_wakeuplight

# On wakeup time start wakeup script
- id: alarm_wakeup
  alias: 'Alarm sound'
  trigger:
    platform: state
    entity_id: sensor.alarm_sensor
  condition:
    condition: state
    entity_id: input_boolean.switch_alarm
    state: "on"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.switch_snoozemode
    - service: script.turn_on
      data:
        entity_id: script.alarm_wakeup

# If media is paused duing snoozemode, wait some minutes and restart wakeup
- id: alarm_snooze
  alias: 'Snooze alarm'
  trigger:
    platform: state
    entity_id: media_player.bedroom_speaker
    from: 'playing'
    to: 'paused'
  condition:
    condition: state
    entity_id: input_boolean.switch_snoozemode
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.alarm_snooze


# Turn off alarm via frontend
- id: alarm_turn_off
  alias: 'Turn off alarm via frontend'
  trigger:
    platform: state
    entity_id: input_boolean.switch_alarm
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.snoozemode
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.alarm_stop

# Set lovelace volume slider to current volume level
- id: set_google_home_slider_position
  alias: Set Google Home Slider Position
  trigger:
    - platform: state
      entity_id: media_player.bedroom_speaker
  condition:
    - condition: template
      value_template: "{{ not is_state_attr('media_player.bedroom_speaker', 'volume_level', states('input_number.home_volume') | int / 100) }}"
  action:
    - service: input_number.set_value
      entity_id: input_number.home_volume
      data_template:
        value: "{{ trigger.to_state.attributes.volume_level | multiply(100) | int }}"

# Set google home volume to value of lovelace slider
- id: set_google_home_volume
  alias: Set Google Home Volume
  trigger:
    - platform: state
      entity_id: input_number.home_volume
  condition:
    - condition: template
      value_template: "{{ not is_state_attr('media_player.bedroom_speaker', 'volume_level', states('input_number.home_volume') | int / 100) }}"
  action:
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data_template:
        volume_level: "{{ states('input_number.home_volume') | int / 100 }}"

- id: ifttt_call
  alias: ifttt call
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    - service_template: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'
        value: '{{ trigger.event.data.value}}'
    - service: script.turn_on
      data:
        entity_id: script.set_alarm_from_temp
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.switch_alarm
