
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

system_log:
  max_entries: 250

  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

#

##################################################################
##################################################################

                          # Lighting

##################################################################

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# add lights
yeelight:
  devices:
    192.168.31.108:
      name: desk
      model: color1
      save_on_change: true
    192.168.31.71:
      name: door
      model: color1
      save_on_change: true
    192.168.31.238:
      name: bed
      model: color1
      save_on_change: true
    192.168.31.126:
      name: couch
      model: color1
      save_on_change: true
    192.168.31.249:
      name: strip
      model: strip1
      save_on_change: true
    192.168.31.57:
      name: cabinet
      model: bslamp1
      save_on_change: true

# create light groups
light:
  - platform: group
    name: bedroom_lights
    entities:
      - light.door
      - light.couch
      - light.bed
      - light.desk
      - light.strip
      - light.cabinet
  - platform: group
    name: wakeup_lights
    entities:
      - light.cabinet
      - light.bed
      - light.desk
      - light.door


##################################################################
##################################################################

                        # Audio & Music

##################################################################

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Spotcast component
spotcast:
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key

##################################################################
##################################################################

                # Input boolean, number & select

##################################################################

# Input numbers
input_number:
  home_volume:
    name: Google Home
    initial: 40
    min: 0
    max: 100
    step: 10
    icon: mdi:volume-high
  snooze_time:
    name: Snooze time (minutes)
    icon: mdi:alarm-snooze
    initial: 7
    min: 1
    max: 30
    step: 1

input_datetime:
  alarm_time:
    name: Alarm time
    has_date: false
    has_time: true

input_boolean:
  advanced_alarm:
    name: Advanced alarm settings
    initial: off
    icon: mdi:cog
  advanced_music:
    name: Advanced music settings
    initial: off
    icon: mdi:cog
  switch_spotify_card:
    name: Spotify playlist card
    initial: off
    icon: mdi:playlist-music
  switch_autoalarm:
    name: Auto set alarm at 22:00
    initial: off
    icon: mdi:alarm-check
  switch_alarm_podcast:
    name: Play podcast after alarm
    icon: mdi:podcast
    initial: on
  switch_music_lights:
    name: Light album art mode
    icon: mdi:music-clef-treble
    initial: off

# Alarm playlist selector
input_select:
  wakeup_music:
    name: 'Wake up to:'
    options:
      - Spotify
      - Radio
      - Podcast
    icon: mdi:alarm-note
  
  spotify_sources:
    name: Spotify source
    icon: mdi:volume-source
    options:
      - HomeAssistant

  spotify_playlist:
    name: 'Playlist:'
    options:
      - Morning Motivation
      - Top of the morning
      - Morning Acoustic
      - Wake Up Happy
      - Wake Up and Smell the Coffee
      - Wake Up Gently
    icon: mdi:spotify

  radio_station:
    name: 'Radio Station:'
    options:
      - Radio 538
      - Q-Music
      - Q-Music Non-Stop
      - 3FM
      - 100% NL
      - Veronica
      - Sky Radio
      - SLAM! FM
      - Arrow Classic Rock
    icon: mdi:radio

  morning_podcast:
    name: 'Podcast:'
    options:
      - NRC vandaag
      - NOS met het oog op morgen
      - VOX today explained
      - TIMES the daily
    icon: mdi:podcast

  alarm_state:
    name: "Alarm current state"
    options:
      - Not set
      - Set
      - Activated
      - Snoozed

  button_cycler:
    name: Xiaomi Button Scene Cycler
    options:
      - Normal
      - Yellow
      - Evening
      - Night
      - Movie


##################################################################
##################################################################

                # Weather

##################################################################
weather:
  - platform: buienradar
    name: buienradar
camera:
  - platform: buienradar

##################################################################
##################################################################

                # Notify

##################################################################

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

##################################################################
##################################################################

                      # Google services

##################################################################

# add google assistant
google_assistant:
  project_id: !secret google_project_id
  service_account: !include service.json
  report_state: false
  exposed_domains:
    - light
  entity_config:
    light.bedroom_lights:
      expose: false
    light.wakeup_lights:
      expose: false
    script.alarm_stop:
      expose: true
    script.alarm_snooze:
      expose: true
    script.yellow_light:
      expose: true
    script.evening_light:
      expose: true
    script.night_light:
      expose: true
    script.movie_light:
      expose: true
    script.normal_light:
      expose: true

# Diagflog and intents for advanced communication via google assistant
dialogflow:
intent_script: !include intents.yaml

# Text to speech
tts:
  - platform: google_translate
    cache: false
    cache_dir: /tmp/tts
    language: "en-us"
    time_memory: 300
    base_url: !secret tts_url
    service_name: google_translate_say