homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include themes.yaml

device_tracker:
  # - platform: xiaomi
  #   host: 192.168.31.1
  #   username: admin
  #   password: !secret router_password
  #   new_device_defaults:
  #     track_new_devices: true
  #     hide_if_away: true
  #   interval_seconds: 30
  #   consider_home: 60
  - platform: bluetooth_tracker

person:
  - name: Mark
    id: markhu
    user_id: 3651c436a5a448a69d3fcbde6ecbd96e
    device_trackers:
      - device_tracker.oneplus6_bt
      - device_tracker.oneplus6_wifi

hacs:
  token: !secret hacs_github_token
  appdaemon: true
  python_script: true
  theme: true
  options:
    country: NL

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# add lights
yeelight:
  devices:
    192.168.31.108:
      name: desk
      model: color1
      save_on_change: true
    192.168.31.71:
      name: door
      model: color1
      save_on_change: true
    192.168.31.238:
      name: bed
      model: color1
      save_on_change: true
    192.168.31.126:
      name: couch
      model: color1
      save_on_change: true
    192.168.31.249:
      name: strip
      model: strip1
      save_on_change: true

# create light groups
light:
  platform: group
  name: bedroom_lights
  entities:
    - light.door
    - light.couch
    - light.bed
    - light.desk
    - light.strip

# add ifttt
ifttt:
  key: !secret ifttt_key

# add google assistant
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
  entity_config:
    light.bedroom_lights:
      expose: false
    script.normal_light:
      expose: true
    script.yellow_light:
      expose: true
    script.evening_light:
      expose: true
    script.night_light:
      expose: true
    script.movie_light:
      expose: true
    script.alarm_stop:
      expose: true
    input_boolean.switch_alarm:
      expose: true

# calendar component
google:
  client_id: !secret calendar_client_id
  client_secret: !secret calendar_client_secret

# Weather component for lovelace Card
weather:
  - platform: buienradar
    name: buienradar
camera:
  - platform: buienradar

# Sensors
sensor: !include sensors.yaml

# Podcast
gpodder:
  username: !secret gpodder_username
  password: !secret gpodder_password
  sensor:
    - enabled: true
      name: gpodder
      device: homecassistant

# Spotify
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      abc123def456: 'Living Room'
      9183abas000: 'Bed Room'
  - platform: mpd
    host: !secret mpd_server_url

# Spotcast component
spotcast:
  username: !secret spotify_login
  password: !secret spotify_password

# Input numbers
input_number:
  home_volume:
    name: Google Home
    initial: 40
    min: 0
    max: 100
    step: 10
    icon: mdi:volume-high
  alarm_hours:
    name: Hour
    icon: mdi:clock
    initial: 7
    min: 0
    max: 23
    step: 1
  alarm_minutes:
    name: Minute
    icon: mdi:clock-outline
    initial: 30
    min: 0
    max: 55
    step: 5
  alarm_temp:
    name: ifttt alarm string temp
    initial: 0
    min: 0
    max: 23.99
    step: 0.01
  snooze_time:
    name: Snooze time (minutes)
    icon: mdi:alarm-snooze
    initial: 7
    min: 1
    max: 30
    step: 1

input_boolean:
  switch_alarm:
    name: Set alarm
    initial: off
    icon: mdi:alarm
  switch_autoalarm:
    name: Auto set alarm at 22:00
    initial: off
    icon: mdi:alarm-check
  switch_alarm_podcast:
    name: Play podcast after alarm
    icon: mdi:podcast
    initial: on
  switch_snoozemode:
    name: Restart media after some minutes
    initial: off
  switch_music_lights:
    name: Light album art mode
    icon: mdi:music-clef-treble
    initial: off

# Alarm playlist selector
input_select:
  wakeup_music:
    name: 'Wake up to:'
    options:
      - Spotify
      - Radio
    icon: mdi:alarm-note

  spotify_playlist:
    name: 'Playlist:'
    options:
      - Kitchen Swagger
      - Morning Motivation
      - Top of the morning
      - Morning Acoustic
      - Wake Up Happy
      - Wake Up and Smell the Coffee
    icon: mdi:spotify

  radio_station:
    name: 'Radio Station:'
    options:
      - Radio 538
      - Q-Music
      - Q-Music Non-Stop
      - 3FM
      - 100% NL
      - Veronica
      - Sky Radio
      - SLAM! FM
      - Arrow Classic Rock
    icon: mdi:radio

  morning_podcast:
    name: 'Podcast:'
    options:
      - NRC vandaag
      - NOS met het oog op morgen
      - VOX today explained
      - TIMES the daily
    icon: mdi:podcast

  alarm_state:
    name: "Alarm current state"
    options:
      - Not set
      - Set
      - Activated
      - Snoozed

# Text to speech
tts:
  - platform: google_translate
    cache: false
    cache_dir: /tmp/tts
    language: "en-us"
    time_memory: 300
    base_url: !secret tts_url
    service_name: google_say

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
