
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

system_log:
  max_entries: 250

recorder: 
  include:
    entities:
      - sensor.miflora_sun
      - sensor.miflora_conductivity
      - sensor.miflora_moisture
      - sensor.miflora_temp
      - sensor.load_5m
      - sensor.cpu_temp
      - sensor.disk_use_percent
      - sensor.memory_use_percent
  purge_keep_days: 5

  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml

##################################################################
##################################################################

                          # Lighting

##################################################################

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# add lights
yeelight:
  devices:
    192.168.1.200:
      name: desk
      model: color1
      save_on_change: true
    192.168.1.238:
      name: door
      model: color1
      save_on_change: true
    192.168.1.190:
      name: bed
      model: color1
      save_on_change: true
    192.168.1.146:
      name: couch
      model: color1
      save_on_change: true
    192.168.1.185:
      name: strip
      model: strip1
      save_on_change: true
    192.168.1.248:
      name: cabinet
      model: bslamp1
      save_on_change: true

# create light groups
light:
  - platform: group
    name: bedroom_lights
    entities:
      - light.door
      - light.couch
      - light.bed
      - light.desk
      - light.strip
      - light.cabinet
  - platform: group
    name: wakeup_lights
    entities:
      - light.cabinet
      - light.bed
      - light.desk
      - light.door


##################################################################
##################################################################

                        # Audio & Music

##################################################################

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Spotcast component
spotcast:
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key


##################################################################
##################################################################

                # Weather

##################################################################
weather:
  - platform: buienradar
    name: buienradar
camera:
  - platform: buienradar

##################################################################
##################################################################

                # Notify

##################################################################

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

##################################################################
##################################################################

                      # Google services

##################################################################

# add google assistant
google_assistant:
  project_id: !secret google_project_id
  service_account: !include service.json
  report_state: false
  exposed_domains:
    - light
  entity_config:
    light.bedroom_lights:
      expose: false
    light.wakeup_lights:
      expose: false
    sensor.miflora_temp:
      expose: true
    script.alarm_stop:
      expose: true
    script.alarm_snooze:
      expose: true
    script.yellow_light:
      expose: true
    script.evening_light:
      expose: true
    script.night_light:
      expose: true
    script.movie_light:
      expose: true
    script.normal_light:
      expose: true
    input_select.alarm_state:
      expose: true
    input_select.wakeup_music:
      expose: true
    media_player.spotify_mark_shui_hu:
      expose: true
      

# Diagflog and intents for advanced communication via google assistant
dialogflow:
intent_script: !include intents.yaml

# Text to speech
tts:
  - platform: google_translate
    cache: false
    cache_dir: /tmp/tts
    language: "en-us"
    time_memory: 300
    base_url: !secret ha_url
    service_name: google_translate_say
