- platform: random

- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    alarm_time_short:
      value_template: "{{ state_attr('input_datetime.alarm_time', 'timestamp') | int | timestamp_custom('%H:%M', False) }}"
      
    alarm_sensor:
      value_template: '{{ states("sensor.time") == states("sensor.alarm_time_short") }}'

    alarm_m10_sensor:
      value_template: '{{ states("sensor.time") == ((state_attr("input_datetime.alarm_time", "timestamp") - 600) | int | timestamp_custom("%H:%M", False)) }}'

    bedroom_speaker_spotify:
      value_template: >
        {% if state_attr("media_player.bedroom_speaker", "app_name") == "Spotify" %} spotify
        {% else %} not_spotify
        {% endif %}

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ "%.2f"|format(value|multiply(0.001)) }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_5m